server {
    listen 80;

    location = / {
        return 301 /5-4-3-2-1-grounding/;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /5-4-3-2-1-grounding/index.html;
    }

    error_page 404 /5-4-3-2-1-grounding/index.html;

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
