server {
    listen 80;
    
    # Required to serve proper Content-Type headers
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Set the root to the default nginx html path
    # Our Docker container places the app at /usr/share/nginx/html/5-4-3-2-1-grounding
    root /usr/share/nginx/html;

    # 1) If the reverse proxy does NOT strip the subpath
    # Example Request: /5-4-3-2-1-grounding/assets/index.css
    location /5-4-3-2-1-grounding {
        try_files $uri $uri/ /5-4-3-2-1-grounding/index.html;
    }

    # 2) If the reverse proxy STRIPS the subpath
    # Example Request: /assets/index.css 
    # Try finding the file internally inside the 5-4-3-2-1-grounding directory
    location / {
        try_files /5-4-3-2-1-grounding$uri /5-4-3-2-1-grounding$uri/ /5-4-3-2-1-grounding/index.html;
    }
}
